package com.fitness.app.presentation.settings.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.fitness.app.ui.theme.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PrivacyPolicyScreen(
    onBack: () -> Unit
) {
    Scaffold(
        containerColor = MaterialTheme.colorScheme.background,
        topBar = {
            CenterAlignedTopAppBar(
                title = { Text("Privacy Policy", fontWeight = FontWeight.Bold) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Back")
                    }
                },
                colors = TopAppBarDefaults.centerAlignedTopAppBarColors(
                    containerColor = MaterialTheme.colorScheme.background
                )
            )
        }
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .padding(horizontal = 24.dp)
                .verticalScroll(rememberScrollState())
        ) {
            Spacer(modifier = Modifier.height(16.dp))
            
            Text(
                "Last Updated: April 9, 2026",
                fontSize = 14.sp,
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                modifier = Modifier.padding(bottom = 16.dp)
            )

            Text(
                "At Eva Smart Ring (\"we,\" \"our,\" or \"us\"), we are committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your information when you visit our website, use the Eva Smart Ring, or interact with our mobile application.",
                fontSize = 14.sp,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                lineHeight = 20.sp,
                modifier = Modifier.padding(bottom = 16.dp)
            )
            
            PolicySection("1. Information We Collect", "We collect information that you provide directly to us, as well as data generated by your use of the smart ring.\n" +
                    "• Personal Information: Name, email address, shipping address, and payment information when you purchase a ring or create an account.\n" +
                    "• Health & Wellness Data: Because the Eva Smart Ring is a wearable health tracker, we collect biometric data such as heart rate, sleep patterns, body temperature, blood oxygen levels (SpO2), and activity metrics (steps, calories).\n" +
                    "• Device Information: Technical data such as your IP address, browser type, operating system, and the unique ID of your Eva Smart Ring.\n" +
                    "• Cookies: We use cookies to improve your browsing experience and analyze website traffic.")
            
            PolicySection("2. How We Use Your Information", "We use the collected data for the following purposes:\n" +
                    "• To Provide Services: To display your health trends and insights within the app.\n" +
                    "• Personalization: To offer tailored wellness recommendations based on your biometric data.\n" +
                    "• Order Fulfillment: To process transactions and ship your Eva Smart Ring.\n" +
                    "• Communication: To send updates, security alerts, and support messages.\n" +
                    "• Improvement: To analyze how our users interact with the device to improve hardware and software performance.")
            
            PolicySection("3. Data Sharing and Disclosure", "We do not sell your personal health data to third parties. We may share information only in the following cases:\n" +
                    "• Service Providers: With vendors who help us with website hosting, payment processing, or shipping.\n" +
                    "• Legal Requirements: If required by law, subpoena, or to protect the safety and rights of our users.\n" +
                    "• Anonymized Data: We may share aggregated, non-identifiable data for research or marketing purposes.")
            
            PolicySection("4. Data Security", "We implement industry-standard security measures, including encryption (SSL/TLS), to protect your sensitive health data. However, no method of transmission over the internet is 100% secure, and we cannot guarantee absolute security.")
            
            PolicySection("5. Your Rights", "Depending on your location (such as the EU under GDPR or California under CCPA), you may have the right to:\n" +
                    "• Access the personal data we hold about you.\n" +
                    "• Request the deletion of your account and health history.\n" +
                    "• Opt-out of marketing communications.\n" +
                    "• Correct inaccurate information.")

            PolicySection("6. Children’s Privacy", "The Eva Smart Ring is not intended for use by individuals under the age of 13 (or 16 in certain jurisdictions). We do not knowingly collect personal data from children.")

            PolicySection("7. Changes to This Policy", "We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new policy on this page and updating the \"Last Updated\" date.")
            
            PolicySection("8. Contact Us", "If you have questions about this Privacy Policy, please contact us at: mdoffice@dkgrouplabs.com")

            Spacer(modifier = Modifier.height(24.dp))
            
            Text(
                "Contact: mdoffice@dkgrouplabs.com",
                fontSize = 14.sp,
                fontWeight = FontWeight.Bold,
                color = NeonCyan,
                modifier = Modifier.padding(bottom = 32.dp)
            )
        }
    }
}

@Composable
private fun PolicySection(title: String, content: String) {
    Column(modifier = Modifier.padding(vertical = 12.dp)) {
        Text(title, fontWeight = FontWeight.Bold, fontSize = 16.sp, color = NeonCyan)
        Spacer(modifier = Modifier.height(4.dp))
        Text(content, fontSize = 14.sp, color = MaterialTheme.colorScheme.onSurfaceVariant, lineHeight = 20.sp)
    }
}
